#!/usr/bin/env bash

BLUE="\033[36m"
BOLD="\033[1m"
NORMAL="\033[0m"

if [ "$1" == "docker" ]; then
  PATHFLOW_VERSION="$(awk '/__version__ = / {gsub(/"/, ""); print $3}' pathflowai/__init__.py)"
  docker build -t docker-pathflowai .
  docker tag docker-pathflowai "sumanthratna/pathflowai:$PATHFLOW_VERSION"
  docker push "sumanthratna/pathflowai:$PATHFLOW_VERSION"
elif [ "$1" == "conda" ]; then
  echo "DOESNT WORK YET"
elif [ "$1" == "pypi" ]; then
  poetry publish --build
elif [ "$1" == "help" ] || [ "$1" == "" ]; then
  echo -e "Usage: ./publish $BLUE<target>$NORMAL"
  echo
  echo -e "$BOLD"Docker"$NORMAL"
  echo -e "  $BLUE"docker"$NORMAL\tPublish to Docker Hub."
  echo
  echo -e "$BOLD"Conda"$NORMAL"
  echo -e "  $BLUE"conda"$NORMAL\t\tPublish to Anaconda Cloud."
  echo
  echo -e "$BOLD"PyPI"$NORMAL"
  echo -e "  $BLUE"pypi"$NORMAL\t\tPublish to PyPI."
else
  echo "Invalid argument"
  exit 2
fi
